PortalSend/Controllers/LotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PortalSend.Models;
namespace PortalSend.Controllers
{
    public class LotesController : Controller
    {
        // GET: Lotes
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ListarLotes(string Fecha_Desde, string Fecha_Hasta)
        {
            List<Lotes_Models> ListarL = new List<Lotes_Models>();
            Lotes_Models L = new Lotes_Models();
            DateTime fechadesde = new DateTime(1900, 01, 01);
            DateTime fechahasta = new DateTime(2050, 12, 31);

            DateTime.TryParse(Fecha_Desde, out fechadesde);
            DateTime.TryParse(Fecha_Hasta, out fechahasta);
            try
            {
                ListarL = L.SelectLotes(fechadesde, fechahasta);

            }
            catch (Exception ex)
            {
                L = new Lotes_Models();
                L.Lote = "ERROR:" + ex.Message;
                L.Cant = -1;
                ListarL.Add(L);
             
            }

            return new JsonResult
            {
                ContentType = "application/json",
                Data = ListarL,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        public JsonResult EliminarLotes(string Lote)
        {
            List<Contactos_Models> ListarL = new List<Contactos_Models>();
            ResultadoCRUD_Models R = new ResultadoCRUD_Models();
            List<ResultadoCRUD_Models> ListR = new List<ResultadoCRUD_Models>();
            try
            {


                
                    R = new ResultadoCRUD_Models();
                    R=new Contactos_Models().DeleteContactosByLote(Lote);
                    ListR.Add(R);
                

            }
            catch (Exception ex)
            {
                R = new ResultadoCRUD_Models();
                R.res_observacion = "ERROR:" + ex.Message;
                R.res_cantidad = -1;
                R.res_metodo = "Lotes.EliminarLotes";
                ListR.Add(R);
            }

            return new JsonResult
            {
                ContentType = "application/json",
                Data = ListR,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }
    }
}

PortalSend/Controllers/ReporteController.cs
using PortalSend.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalSend.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ListarReporte(string Fecha_Desde, string Fecha_Hasta)
        {
            List<Reporte_Envios_Models> ListarL = new List<Reporte_Envios_Models>();
            Reporte_Envios_Models L = new Reporte_Envios_Models();
            DateTime fechadesde = new DateTime(1900, 01, 01);
            DateTime fechahasta = new DateTime(2050, 12, 31);

            DateTime.TryParse(Fecha_Desde, out fechadesde);
            DateTime.TryParse(Fecha_Hasta, out fechahasta);
            try
            {
                ListarL = L.SelectMensajesEnviados(fechadesde, fechahasta);

            }
            catch (Exception ex)
            {
                L = new Reporte_Envios_Models();
                L.men_cuerpo = "ERROR:" + ex.Message;
                L.men_phone ="-1";
                ListarL.Add(L);

            }

            return new JsonResult
            {
                ContentType = "application/json",
                Data = ListarL,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }


        public ActionResult Inbox()
        {
            return View();
        }


        public JsonResult ListarInbox()
        {
            List<Inbox_Models> ListarL = new List<Inbox_Models>();
            try
            {
                ListarL = new Inbox_Models().GetInbox();

            }
            catch (Exception ex)
            {
                ListarL.Add(new Inbox_Models() { id = -1, content = ex.Message });
            }

            return new JsonResult
            {
                ContentType = "application/json",
                Data = ListarL,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }


    }
}

PortalSend/Controllers/SMSController.cs
using PortalSend.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hangfire;
using Hangfire.SqlServer;


namespace PortalSend.Controllers
{
    public class SMSController : Controller
    {

        // GET: SMS
        public ActionResult Index()
        {
            try
            {

           

            
            ViewData["Resultado1"]=SynWayAPI_models.Consultas(SynWayAPI_models.Consultas_Types.GetPortInfo);
            ViewData["Resultado2"] = SynWayAPI_models.Consultas(SynWayAPI_models.Consultas_Types.GetPortConnectState);
            ViewData["Resultado3"] = SynWayAPI_models.Consultas(SynWayAPI_models.Consultas_Types.GetWirelessinfo);
            ViewData["Resultado4"] = SynWayAPI_models.Consultas(SynWayAPI_models.Consultas_Types.GetDetailPortInfo);
            
            /*ViewData["Resultado5"] = SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS,"2616142278","1","prueba:"+ DateTime.Now.ToShortTimeString());
            ViewData["Resultado6"] = SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS, "2616142278", "1", "prueba:" + DateTime.Now.ToShortTimeString());
            */
            /*
            BackgroundJob.Schedule(() => SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS, "2616142278", "1", "prueba:" + DateTime.Now.ToShortTimeString()),
                TimeSpan.FromMinutes(1));

                BackgroundJob.Schedule(() => SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS, "2616142278", "1", "prueba:" + DateTime.Now.ToShortTimeString()),
                TimeSpan.FromMinutes(2));


                BackgroundJob.Schedule(() => SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS, "2616142278", "1", "prueba:" + DateTime.Now.ToShortTimeString()),
                TimeSpan.FromMinutes(3));
          */

                //  BackgroundJob.Enqueue(() => SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS, "2616142278", "1", "prueba:" + DateTime.Now.ToShortTimeString()) );
                /*
                using (new BackgroundJobServer())
                {
                    Console.ReadLine();
                }
                */

            }
            catch (Exception ex)
            {

                throw;
            }

            return View();
        }
        public ActionResult EnviarSMS(string Lote)
        {
            ViewData["Lote"] = Lote;
         //   ViewData["Configuración"] = new Chiperas_Configuration_Models();

            return View();
        }



        public JsonResult ListarContactos(string Lote)
        {
            List<Contactos_Models> ListarC = new List<Contactos_Models>();
            Contactos_Models C = new Contactos_Models();
         
            try
            {
                ListarC = new Contactos_Models().SelectContactos(Lote);

            }
            catch (Exception ex)
            {
                C = new Contactos_Models();
                C.con_titular = "ERROR:" + ex.Message;
                C.con_phone = "-1";
                ListarC.Add(C);

            }

            return new JsonResult
            {
                ContentType = "application/json",
                Data = ListarC,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        public JsonResult EnviarSMSMasivo(string Mensaje, string Lote, string reporte, string Port, string Times )
        {

            List<Resultados_Models> ListarR = new List<Resultados_Models>();
            Resultados_Models R = new Resultados_Models();
            Mensajes_Models M = new Mensajes_Models();

            try
            {
                List<Contactos_Models> ListarM = new List<Contactos_Models>();

                ListarM = new Contactos_Models().SelectContactos(Lote);
                string _loteenvio = DateTime.Now.ToString("yyMMdd-HHmmss");
                int i=0;
                int _Times = 10;
                 int.TryParse(Times, out _Times);

                //Acuse de inicio
                //SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS,reporte , Port, DateTime.Now.ToString("dd/MM/yy HH:mm:ss")+" Iniciado:"+ListarM.Count+" items."+ "Envio: " + _loteenvio + " Segs:" + _Times + " Puerto:" + Port.ToString());
                Mensajes_Models.EnviarSMS(reporte, Port, DateTime.Now.ToString("dd/MM/yy HH:mm:ss") + " Iniciado:" + ListarM.Count + " items." + "Envio: " + _loteenvio + " Segs:" + _Times + " Puerto:" + Port.ToString());

                //Envios
                foreach (Contactos_Models item in ListarM)
                {
                    M = new Mensajes_Models();
                    
                    M.mencon_id = item.con_id;
                    M.men_phone = item.con_phone;
                    M.mencon_id = item.con_id;
                    M.men_cant = 1;
                    M.men_cuerpo = Mensaje;
                    M.men_enviolote = _loteenvio;
                    M.men_estado = "ERROR";
                    M.men_fecha = DateTime.Now;
                    M.men_fechamodif = DateTime.Now;
                    M.men_lote = item.con_lote;
                    M.men_phone = item.con_phone;
                    M.men_taskid = 0;
                    ResultadoCRUD_Models rm = M.InsertUpdateMensajes(M);
                    
                    //No pudo crear el mensaje en la base. Se sale del proceso
                    if(rm.res_cantidad==-1)
                    {
                        R = new Resultados_Models();
                        R.res_mensaje = "ERROR al crear el mensaje el la BD:" + rm.res_excepcion;
                        R.res_excepcion = "-1";
                        ListarR.Add(R);
                    }
                    else
                    {
                        R = new Resultados_Models();
                        M.men_id = int.Parse(rm.res_id);
                        //ID de Tarea
                        R.res_id = int.Parse(BackgroundJob.Schedule(() => Mensajes_Models.EnviarSMS(item.con_phone, Port, Mensaje, M.men_id), TimeSpan.FromSeconds(_Times)));
                        i++;
                       
                        //guardo el número de tarea
                        M.men_taskid = R.res_id;
                        rm = new ResultadoCRUD_Models();
                        rm=M.InsertUpdateMensajes(M);
                        if (rm.res_cantidad == -1)
                        {
                            R = new Resultados_Models();
                            R.res_mensaje = "ERROR al crear el mensaje el la BD:" + rm.res_excepcion;
                            R.res_excepcion = "-1";
                            ListarR.Add(R);
                        }



                        R.res_mensaje = "Se ha creado la tarea:" + R.res_id.ToString();
                        R.res_contenido = new ReturnValue() { content = "Envio: " + _loteenvio + " Segs:" + _Times + " Puerto:" + Port.ToString(), result = "OK" };
                        M.men_estado = "Creado";
                        M.men_taskid = R.res_id;
                        ListarR.Add(R);
                    }    
                    
                }

                //Acuse de envio realizado
                BackgroundJob.Schedule(() => SynWayAPI_models.EnvioSMS(SynWayAPI_models.Envios_Types.SendSMS, reporte, Port, DateTime.Now.ToString("dd/MM/yy HH:mm:ss") + " Envio programado:" + ListarM.Count + " items" + "Envio: " + _loteenvio + " Segs:" + _Times + " Puerto:" + Port.ToString())
                         , TimeSpan.FromSeconds(i));

            }
            catch (Exception ex)
            {
                R = new Resultados_Models();
                R.res_mensaje = "ERROR:" + ex.Message;
                R.res_excepcion= "-1";
                ListarR.Add(R);

            }

            return new JsonResult
            {
                ContentType = "application/json",
                Data = ListarR,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };

           

        }



    }
}

PortalSend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-ar"> 
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")


    @Styles.Render("~/Content/css")


    <!-- KENDO CORE -->
    <link href="http://kendo.cdn.telerik.com/2020.2.617/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://kendo.cdn.telerik.com/2020.2.617/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://kendo.cdn.telerik.com/2020.2.617/js/kendo.ui.core.min.js"></script>
    <script src="http://kendo.cdn.telerik.com/2020.2.617/js/cultures/kendo.culture.es-AR.min.js"></script>
    <script>
        kendo.culture("es-AR"); // change the culture
    </script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Lato:400,300,700,900" rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    

    <title>@ViewBag.Title - PORTALSEND</title>





</head>
<body>


    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container">

            <div class="logo float-left">
                <h1 class="text-light"><a href="~/"><span>PortalSend</span></a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu float-right d-none d-lg-block">
                <ul>
                    <li class="active"><a href="@Url.Action("Index","SMS")">Home</a></li>
                    <li><a href="@Url.Action("Index","Lotes")">Lotes</a></li>
                    <li><a href="@Url.Action("Index","FileUpload")">Upload</a></li>
                    <li><a href="@Url.Action("Inbox","Reporte")">Inbox</a></li>
                    <li><a href="@Url.Action("Index","Reporte")">Reporte</a></li>

                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header><!-- End #header -->
    <main id="main">



        @RenderBody()

    </main>


        <!-- ======= Footer ======= -->
        <footer id="footer">
            <div class="container">
                <div class="copyright">
                    &copy; Copyright <strong><span>Amoeba</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-one-page-bootstrap-template-amoeba/ -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
        </footer><!-- End #footer -->

        <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>





</body>
</html>

PortalSend/Views/Shared/_Layout_Simple.cshtml
@using System.Configuration;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
</head>
<body>
    @RenderBody()
</body>
</html>